version: '3'

services:
  postgres-service:
    image: postgres
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "admin"
      POSTGRES_DB: "clube_da_luta"
    ports:
      - "15432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - ebac-network

  pgadmin-service:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: "rpires@admin.com"
      PGADMIN_DEFAULT_PASSWORD: "admin"
    ports:
      - "16543:80"
    depends_on:
      - postgres-service
    networks:
      - ebac-network

  mysql-service:
    image: mysql/mysql-server:latest
    environment:
      MYSQL_ROOT_PASSWORD: "admin"
      MYSQL_DATABASE: "postgres"
      MYSQL_USER: "admin"
      MYSQL_PASSWORD: "admin"
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - ebac-network

networks:
  ebac-network:
    driver: bridge

volumes:
  postgres-data:
  mysql-data:
